### ISSUE TITLE
Image caching segfaults in sfml port.

### ISSUE THREAD

**Issue by lambda-11235** [Secretchronicles/TSC#501]
Recaching images causes a segfault in feature-sfml-port2.

**Comment by Quintus** [comment]
I can reproduce this. GDB run with Stacktrace:

~~~~~
% gdb ./TESTINSTALL/bin/tsc 
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from ./TESTINSTALL/bin/tsc...done.
(gdb) r
Starting program: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/bin/tsc 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Initializing resource manager and core classes
Game data directory: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc
User data directory: /home/quintus/.local/share/tsc
User cache directory: /home/quintus/.cache/tsc
User config directory: /home/quintus/.config/tsc
Initializing Package Manager
Configuration file is '/home/quintus/.config/tsc/config.xml'.
Translation locale is de_DE.UTF-8
Translation support with gettext set to:
	Directory /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/translations
	Codeset: UTF-8
	Text domain: Secretchronicles
[New Thread 0x7fffe64ec700 (LWP 25370)]
[Thread 0x7fffe64ec700 (LWP 25370) exited]
[New Thread 0x7fffe64ec700 (LWP 25372)]
CEGUI log file is at '/home/quintus/.cache/tsc/cegui.log'.
[New Thread 0x7fffe580a700 (LWP 25373)]
Loading campaigns
Loaded campaign file: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/campaigns/tutorial.tsccpn
Loaded campaign file: /home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/campaigns/smc.tsccpn
Setting up level player
Loading levels
Applying preferences
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/slime/1.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_black.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_yellow.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_blue.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_white.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_green.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/2_1.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_grey.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/2_2.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/brick/1_red.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/cloud/1.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/screw/1.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/wood/2.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/wood/1.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/right_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/right_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/left_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/middle.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/left.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/left_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/green/right.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/right_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/right_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/left_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/middle.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/left.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/left_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/orange/right.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/right_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/right_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/left_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/middle.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/left.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/left_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/red/right.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/right_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/right_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/left_up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/middle.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/left.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/up.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/left_down.png Unknown bytes per pixel 8
Warning: cVideo :: Save_Surface : /home/quintus/.cache/tsc/images/1024x768/pixmaps/blocks/pipe/connection/plastic_1/blue/right.png Unknown bytes per pixel 8

Program received signal SIGSEGV, Segmentation fault.
0x0000000000785620 in TSC::cVideo::Downscale_Image (this=0xdd4e30, orig=0x18c11b0 "", width=512, height=512, channels=8, resampled=0x1701430 "", block_size_x=4, block_size_y=4)
    at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/video/video.cpp:1508
1508	                        sum_value += orig[index + v * width * channels + u * channels];
(gdb) bt
#0  0x0000000000785620 in TSC::cVideo::Downscale_Image (this=0xdd4e30, orig=0x18c11b0 "", width=512, height=512, channels=8, resampled=0x1701430 "", block_size_x=4, block_size_y=4)
    at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/video/video.cpp:1508
#1  0x0000000000782174 in TSC::cVideo::Init_Image_Cache (this=0xdd4e30, recreate=false, draw_gui=true) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/video/video.cpp:620
#2  0x00000000007b2eb6 in TSC::Init_Game () at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:305
#3  0x00000000007b23ed in main (argc=1, argv=0x7fffffffe878) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/core/main.cpp:180
(gdb) p width
$1 = 512
(gdb) p height
$2 = 512
(gdb) p block_size_x
$3 = 4
(gdb) p block_size_y
$4 = 4
(gdb) p orig
$5 = (const unsigned char * const) 0x18c11b0 ""
(gdb) p resampled
$6 = (unsigned char *) 0x1701430 ""
(gdb) up 1
#1  0x0000000000782174 in TSC::cVideo::Init_Image_Cache (this=0xdd4e30, recreate=false, draw_gui=true) at /home/quintus/repos/privat/projekte/c++/TSC/tsc/src/video/video.cpp:620
620	        bool downsampled = Downscale_Image(static_cast<const unsigned char*>(p_sf_image->getPixelsPtr()), p_sf_image->getSize().x, p_sf_image->getSize().y, image_bpp, image_downsampled, reduce_block_x, reduce_block_y);
(gdb) p filename
$7 = {static preferred_separator = 47 '/', m_pathname = "/home/quintus/repos/privat/projekte/c++/TSC/tsc/build/TESTINSTALL/share/tsc/pixmaps/blocks/pipe/connection/metal_1/grey/middle.png"}
(gdb) 
~~~~~

Might be related to [this unconverted statement from old SDL-based code](https://github.com/Secretchronicles/TSC/blob/f1a7838e6265ac2fb154ec24cfeaf778dd39c561/tsc/src/video/video.cpp#L616-L620). These warnings shouldn’t be there.

Also, excuse my ignorance, shouldn’t an image have **bits per pixel**, and not **bytes per pixel**?

Vale,
Quintus

**Comment by Quintus** [comment]
Bytes per pixel is an SDL invention: https://wiki.libsdl.org/SDL_PixelFormat

It’s the number of bytes needed to store a complete pixel. If the image has a colour depth of 8 bits, then an RGB image has 3x8 = 24 bits per pixel. 24 bits can be stored in 3 bytes, so SDL says the image has 3 bytes per pixel.

**Comment by Quintus** [comment]
Commit 0b82e789f4e55afafa00c58d6ecaad8480bc65dd should have fixed the problem. Update your copy of the code and try again.

Vale,
Quintus

**Comment by lambda-11235** [comment]
@Quintus commit 0b82e78 fixed it.

**Comment by Quintus** [comment]
Taran Lynn <notifications@github.com> writes:

> @Quintus commit 0b82e78 fixed it.

Thank you for confirming. This issue is set to autoclose on merging to
devel, so I won’t further touch it.

-- 
#!/sbin/quintus
Blog: http://www.guelkerdev.de

GnuPG key: F1D8799FBCC8BC4F
